[project]
name = "one-key-install"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "jay.zbox.linux", email = "jay.zhangjunjie@outlook.com"},
]
dependencies = ["rich", "fire>=0.7.0", "art>=6.5"]
requires-python = ">=3.6"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true


[project.scripts]
# RobopadStartService = "robopad.cli:main"
# RobopadStartServer = "robopad.server:main"
OneKeyInstall = "one_key_install:main"