[project]
name = "one-key-install"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "jay.zbox.linux", email = "jay.zbox.linux.com"},
]
dependencies = []
requires-python = ">=3.6"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true
